openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0

paths:
  /products:
    get:
      summary: Recherche de produits
      parameters:
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/q"
      responses:
        "200":
          description: Liste de produits trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                multipleProducts:
                  summary: Plusieurs produits
                  value:
                    - name: "Pomme"
                      expiration_datetime: "2025-12-31T23:59:59Z"
                      price: 1.5
                    - name: "Banane"
                      expiration_datetime: "2025-08-31T12:00:00Z"
                      price: 0.8
                emptyList:
                  summary: Aucun produit trouvé
                  value: []

components:
  parameters:
    limit:
      name: limit
      in: query
      description: Nombre maximum d'éléments à retourner
      required: false
      schema:
        type: integer
      example: 10

    q:
      name: q
      in: query
      description: Terme de recherche pour filtrer les produits
      required: false
      schema:
        type: string
      example: "fruit"

  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
      required:
        - name
        - expiration_datetime
        - price
